version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing pnpm...
      - npm install -g pnpm
  pre_build:
    commands:
      - echo Installing dependencies...
      - pnpm install --frozen-lockfile
  build:
    commands:
      - echo Build started on `date`
      - echo Building production bundle...
      - pnpm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying to S3...
      - aws s3 sync dist/ s3://$S3_BUCKET/ --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
      - echo Deployment complete!

artifacts:
  files:
    - '**/*'
  base-directory: dist
