version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing latest pnpm...
      - npm install -g pnpm@latest
  pre_build:
    commands:
      - echo Installing dependencies...
      - pnpm install --no-frozen-lockfile
  build:
    commands:
      - echo Build started on `date`
      - echo Building production bundle...
      - export VITE_BACKEND_URL=https://api.kalifinder.com
      - export VITE_WIDGET_CDN_URL=https://cdn.kalifinder.com
      - pnpm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying to S3 with optimized caching...
      - echo Uploading HTML files with no caching...
      - aws s3 sync dist/ s3://$S3_BUCKET/ --delete --exclude "*" --include "*.html" --cache-control "no-cache, must-revalidate"
      - echo Uploading JS/CSS files with long-term caching and content hash...
      - aws s3 sync dist/ s3://$S3_BUCKET/ --exclude "*.html" --include "*.js" --include "*.css" --content-type "application/javascript" --cache-control "public, max-age=31536000, immutable"
      - echo Uploading other assets with 1-day cache...
      - aws s3 sync dist/ s3://$S3_BUCKET/ --exclude "*.html" --exclude "*.js" --exclude "*.css" --cache-control "public, max-age=86400"
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
      - echo Deployment complete!

artifacts:
  files:
    - '**/*'
  base-directory: dist
