import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  important: ':host',
  safelist: [
    // Semantic color utilities
    'bg-background',
    'bg-primary',
    'bg-secondary',
    'bg-muted',
    'bg-accent',
    'bg-input',
    'bg-card',
    'bg-popover',
    'text-foreground',
    'text-primary',
    'text-secondary',
    'text-muted-foreground',
    'text-primary-foreground',
    'text-secondary-foreground',
    'text-card-foreground',
    'text-popover-foreground',
    'border-border',
    'border-primary',
    'border-secondary',
    'border-input',
    // Layout utilities
    'flex',
    'flex-1',
    'items-center',
    'justify-center',
    'justify-between',
    'gap-2',
    'gap-4',
    'gap-6',
    'w-full',
    'w-70',
    'h-full',
    'p-4',
    'px-4',
    'py-4',
    'py-6',
    'px-12',
    'rounded-lg',
    'rounded-full',
    'rounded-md',
    // Responsive utilities
    'lg:px-12',
    'lg:block',
    'lg:flex',
    'lg:w-auto',
    'lg:gap-6',
    'lg:text-[18px]',
    'lg:text-[16px]',
    'lg:text-xl',
    'md:px-0',
    // State utilities
    'hover:bg-primary-hover',
    'hover:border-primary/50',
    'focus-within:border-primary',
    'focus-within:shadow-md',
    'sticky',
    'top-0',
    'z-50',
    // Animation utilities
    'animate-in',
    'fade-in',
    'zoom-in',
    'slide-in-from-bottom-2',
    'duration-300',
    'duration-500',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
      },
    },
  },
  plugins: [],
} satisfies Config;
