import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  // Don't use :host as important - it causes issues in Shadow DOM
  // Instead, we'll use !important in specific CSS rules where needed
  important: false,
  safelist: [
    // Semantic color utilities
    'bg-background',
    'bg-white',
    'bg-primary',
    'bg-secondary',
    'bg-muted',
    'bg-accent',
    'bg-input',
    'bg-card',
    'bg-popover',
    'text-foreground',
    'text-primary',
    'text-secondary',
    'text-muted-foreground',
    'text-primary-foreground',
    'text-secondary-foreground',
    'text-card-foreground',
    'text-popover-foreground',
    'border-border',
    'border-primary',
    'border-secondary',
    'border-input',
    // Layout utilities
    'flex',
    'flex-1',
    'flex-col',
    'items-center',
    'justify-center',
    'justify-between',
    'justify-end',
    'justify-start',
    'gap-2',
    'gap-3',
    'gap-4',
    'gap-6',
    'gap-[10px]',
    'w-full',
    'w-70',
    'w-4',
    'w-5',
    'h-full',
    'h-4',
    'h-5',
    'p-4',
    'px-4',
    'px-3',
    'py-2',
    'py-4',
    'py-6',
    'px-12',
    'pb-2',
    'pt-4',
    'mb-4',
    'mr-4',
    'mr-[8px]',
    'gap-[8px]',
    'rounded',
    'rounded-lg',
    'rounded-full',
    'rounded-md',
    'rounded-sm',
    'min-w-[8rem]',
    'min-w-[10rem]',
    'flex-shrink-0',
    // Responsive checkbox sizes
    'sm:h-4',
    'sm:w-4',
    'sm:h-5',
    'sm:w-5',
    'lg:h-5',
    'lg:w-5',
    // Responsive utilities
    'lg:px-12',
    'lg:block',
    'lg:flex',
    'lg:w-auto',
    'lg:gap-6',
    'lg:text-[18px]',
    'lg:text-[16px]',
    'lg:text-xl',
    'md:px-0',
    'md:min-w-[10rem]',
    // State utilities
    'hover:bg-primary-hover',
    'hover:bg-accent',
    'hover:text-accent-foreground',
    'hover:border-primary/50',
    'focus-within:border-primary',
    'focus-within:shadow-md',
    'shadow-md',
    'focus:bg-accent',
    'focus:text-accent-foreground',
    'disabled:cursor-not-allowed',
    'disabled:opacity-50',
    'cursor-pointer',
    'sticky',
    'absolute',
    'relative',
    'top-0',
    'top-[0px]',
    'top-1/2',
    'bottom-0',
    'left-0',
    'left-3',
    'right-0',
    'right-3',
    'z-50',
    'z-[2147483647]',
    // Text sizing for filters
    'text-[12px]',
    'text-[14px]',
    'text-[16px]',
    'text-[18px]',
    'text-sm',
    'text-xs',
    'lg:text-[14px]',
    'lg:text-[16px]',
    // Animation utilities
    'animate-in',
    'fade-in',
    'zoom-in',
    'slide-in-from-bottom-2',
    'duration-300',
    'duration-500',
    // Radix UI states
    'data-[state=open]:animate-in',
    'data-[state=closed]:animate-out',
    'data-[state=closed]:fade-out-0',
    'data-[state=open]:fade-in-0',
    'data-[state=closed]:zoom-out-95',
    'data-[state=open]:zoom-in-95',
    'data-[side=bottom]:slide-in-from-top-2',
    'data-[side=left]:slide-in-from-right-2',
    'data-[side=right]:slide-in-from-left-2',
    'data-[side=top]:slide-in-from-bottom-2',
    // Transform utilities
    'transform',
    '-translate-y-1/2',
    'translate-y-0',
    'translate-y-4',
    'translate-x-0',
    'scale-95',
    'scale-105',
    'scale-110',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
      },
    },
  },
  plugins: [],
} satisfies Config;
